dotnet outdated "Chapter 2-4/SampleAPI" -u -pre Always
dotnet outdated "Chapter 5/SampleAPI" -u -pre Always
dotnet outdated "Chapter 6/SampleAPI" -u -pre Always
dotnet outdated "Chapter 7/SampleAPI" -u -pre Always
dotnet outdated "Chapter 8/Catalog" -u -pre Always
dotnet outdated "Chapter 9/Catalog" -u -pre Always
dotnet outdated "Chapter 10/Catalog" -u -pre Always
dotnet outdated "Chapter 11/Catalog" -u -pre Always
dotnet outdated "Chapter 12/Catalog" -u -pre Always
dotnet outdated "Chapter 13/Catalog" -u -pre Always
dotnet outdated "Chapter 13/Cart" -u -pre Always
dotnet outdated "Chapter 15/Catalog" -u -pre Always
dotnet outdated "Chapter 15/Cart" -u -pre Always
dotnet outdated "Chapter 16/Catalog" -u -pre Always
dotnet outdated "Chapter 16/Cart" -u -pre Always
dotnet outdated "Chapter 17/Catalog" -u -pre Always
dotnet outdated "Chapter 17/Cart" -u -pre Always
dotnet outdated "Chapter 18/Catalog" -u -pre Always
dotnet outdated "Chapter 18/Catalog" -u -pre Always
dotnet outdated "Chapter 18/Cart" -u -pre Always 
dotnet outdated "Chapter 19/Catalog" -u -pre Always
dotnet outdated "Chapter 19/Cart" -u -pre Always