dotnet outdated "Chapter 8/Catalog" -u
dotnet outdated "Chapter 9/Catalog" -u
dotnet outdated "Chapter 10/Catalog" -u
dotnet outdated "Chapter 11/Catalog" -u
dotnet outdated "Chapter 12/Catalog" -u
dotnet outdated "Chapter 13/Catalog" -u
dotnet outdated "Chapter 13/Cart" -u
dotnet outdated "Chapter 15/Catalog" -u
dotnet outdated "Chapter 15/Cart" -u
dotnet outdated "Chapter 16/Catalog" -u
dotnet outdated "Chapter 16/Cart" -u
dotnet outdated "Chapter 17/Catalog" -u
dotnet outdated "Chapter 17/Cart" -u
dotnet outdated "Chapter 18/Catalog" -u
dotnet outdated "Chapter 18/Cart" -u
dotnet outdated "Chapter 19/Catalog" -u
dotnet outdated "Chapter 19/Cart" -u